[package]
name = "oracles-offchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
almost-raft = "0.3.0"
async-trait = "0.1.77"
uuid = { version = "1.7.0", features = ["v4"] }
clap = { version = "4.5.1", features = ["derive"] }
serde = "1.0.197"
tokio-serde = {version ="0.9", features = ["json", "cbor"] }
tokio-util = { version = "0.7", features = ["full"] }
futures = "0.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
dashmap = "5.5.3"
rand = "0.8.5"